GET http://localhost:8088/ebook;
###

GET http://localhost:8080/ebookLike?name=vue
###

GET http://localhost:8080/ebookLikeReq?name=vue
###

GET http://localhost:8080/ebookLikeReqResp?name=vue
###

GET http://localhost:8088/ebookLike
###

GET http://localhost:8088/ebookList
###

GET http://localhost:8088/ebook/list
###


GET http://localhost:8088/ebook/list?page=1&size=101
###

